version: '3.8'

services:
  # Kibana
  kibana:
    image: kibana:9.0.2
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - pricing-network
  
  # Elastic Search
  elasticsearch:
    image: elasticsearch:9.0.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - pricing-network
  
  # RabbitMq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - pricing-network
  
  # PriceManager
  price-manager:
    build:
      context: ./src
      dockerfile: PriceManager/Dockerfile
    container_name: price-manager
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      kibana:
          condition: service_started
    environment:
      - RabbitMq__ConnectionString=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:80
    networks:
      - pricing-network
        
  # PriceReader
  price-reader:
    build:
      context: ./src
      dockerfile: PriceReader/Dockerfile
    container_name: price-reader
    ports:
      - "8081:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      kibana:
        condition: service_started
    environment:
      - RabbitMq__ConnectionString=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:80
    networks:
      - pricing-network
        
  # PriceWriter
  price-writer:
    build:
      context: ./src
      dockerfile: PriceWriter/Dockerfile
    container_name: price-writer
    ports:
      - "8082:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      kibana:
        condition: service_started
    environment:
      - RabbitMq__ConnectionString=amqp://guest:guest@rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=http://+:80
    networks:
      - pricing-network

volumes:
  elasticsearch-data:
  rabbitmq_data:

networks:
  pricing-network:
    driver: bridge